# -*- coding: utf-8 -*-
"""Binary Search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-lmf9E5QalBwPuh9EOzn98ZIebozQ2g
"""

def binary_search(arr, target):

    left, right = 0, len(arr) - 1

    print("\n Binary Search Complexity Analysis ")
    print(f"Input size (n): {len(arr)}")
    print("Time Complexity: O(log n) [Logarithmic]")

    while left <= right:
        mid = (left + right)
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

size = int(input("Enter the size of the array: "))
user_arr = [int(input(f"Enter element {j+1}: ")) for j in range(size)]
search = int(input("Enter the element you want to search for: "))

user_arr.sort()
result = binary_search(user_arr, search)

print("-" * 20)
print(f"Sorted Array used for search: {user_arr}")
if result != -1:
    print(f"Element {search} found at index {result}.")
else:
    print(f"Element {search} not found in the list.")

def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

size = int(input("Enter the size of the array: "))
user_arr = [int(input(f"Enter element {j+1}: ")) for j in range(size)]
search = int(input("Enter the element you want to search for: "))

user_arr.sort()
result = binary_search(user_arr, search)

print("\n" + "-" *30)
print(f"Sorted Array used for search: {user_arr}")

if result != -1:
    print(f"Element {search} found at index {result}.")
else:
    print(f"Element {search} not found in the list.")

print("-" * 30)
print("Binary Search Complexity Analysis:")
print(f"Input size (n): {len(user_arr)}")
print(" Time Complexity: (Big O)")
print(" Best Case: O(1)")
print(" Avg/Worst Case: O(log n)")
print(" Space Complexity: O(1)")

def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right)
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

user_input_str = input("Enter integers separated by spaces : ")
user_arr = sorted(list(map(int, user_input_str.split())))

element_to_find = int(input("Enter the element you want to search for: "))

result_index = binary_search(user_arr, element_to_find)

print("-" * 20)
print(f"Sorted Array: {user_arr}")
if result_index != -1:
    print(f"Element {element_to_find} found at index {result_index}.")
else:
    print(f"Element {element_to_find} not found in the list.")